# -*- coding: utf-8 -*-
"""Tarea 1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18gQrIoHNNVpzHLwbZ5KBdFTk6nWKKfwS

Actualizacion de software y instalacion de librerias
"""

!apt update
!pip install -U bnlearn
!pip install -U matplotlib==3.3.4

"""Importacion de librerias y lectura de dataset"""

import pandas as pd
import bnlearn as bn
 
df = pd.read_csv("dataset.csv")
 
print(df)

"""Creacion de modelo"""

model = bn.structure_learning.fit(df)
G = bn.plot(model)

model_update = bn.parameter_learning.fit(model, df)
Gg = bn.plot(model_update, interactive=True, params_interactive={'notebook':True})

"""Primera inferencia"""

q_1 = bn.inference.fit(model_update, variables=['work_type'], evidence={'stroke':1})

"""Segunda Inferencia"""

q_2 = bn.inference.fit(model_update, variables=['stroke'], evidence={'hypertension':1})

q_3 = bn.inference.fit(model_update, variables=['stroke'], evidence={'hypertension':0})

"""Tercera inferencia"""

q_4 = bn.inference.fit(model_update, variables=['heart_disease'], evidence={'hypertension':1})

q_5 = bn.inference.fit(model_update, variables=['heart_disease'], evidence={'hypertension':0})

"""Cuarta inferencia"""

q_6 = bn.inference.fit(model_update, variables=['heart_disease','stroke'], evidence={'hypertension':0})

q_7 = bn.inference.fit(model_update, variables=['heart_disease','stroke'], evidence={'hypertension':1})

"""Quinta inferencia"""

q_8 = bn.inference.fit(model_update, variables=['hypertension'], evidence={'gender':0})

q_9 = bn.inference.fit(model_update, variables=['hypertension'], evidence={'gender':1})